### ISSUE TITLE
Unable to Perform on AlertView Clicks and Swipe guesture actions remotely

### ISSUE THREAD

**Issue by perlasivakrishna** [cobrowseio/cobrowse-sdk-ios-binary#1]
Hello
 In remote Connection Unable to respond to alertviews and swipe gestures and tap gestures. Please check and let me know the update. 

Regards
Siva Krishna

**Comment by headlessme** [comment]
Hi Siva, unfortunately due to limitations of the Apple APIs for UIAlertController we can't support them without using private APIs. If you email us at hello@cobrowse.io we can provide some more information on how you can support them if private API use is available to you.

**Comment by qadirsuh** [comment]
@perlasivakrishna I am having same problem. do you have any workaround?
@headlessme Hello. I am having same issue. Can you please provide some information? I have sent email to hello@cobrowse.io already.

**Comment by snyderj** [comment]
@qadirsuh just replied to your email. Let us know if any further questions we can help with!
