### ISSUE TITLE
Archiving failed due to bitcode

### ISSUE THREAD

**Issue by perlasivakrishna** [cobrowseio/cobrowse-sdk-ios-binary#3]
![screen shot 2018-10-31 at 12 23 36 pm](https://user-images.githubusercontent.com/6779941/47771130-1107c980-dd08-11e8-89c1-1fbf4648705e.png)
May i know what is the fix for this 

Regards
Siva Krishna

**Comment by headlessme** [comment]
Hi Siva, which version of the SDK are you using? We fixed a regression issue related to bitcode in 1.6.3, so make sure you're on at least that version.

**Comment by headlessme** [comment]
Hopefully this resolved your issue, if not please re-open.

**Comment by perlasivakrishna** [comment]
@headlessme It seems fine now. May i know what was the change in the back end.

**Comment by headlessme** [comment]
There was an issue in our release process related to an Xcode 10 upgrade, that caused bitcode to be missed out of the final target.
