### ISSUE TITLE
Unable to build Xcode10.2 in all simulators

### ISSUE THREAD

**Issue by perlasivakrishna** [cobrowseio/cobrowse-sdk-ios-binary#6]
Can u help me with that. but same is getting compiled in real device. 

/Users/sivakrishna/Documents/_Work area/Sendaride-ios/SendASitter/Pods/CobrowseIO/CobrowseIO.framework/CobrowseIO compiled with older version of Swift language (unknown ABI version 0x06) than previous files (unknown ABI version 0x07) file '/Users/sivakrishna/Documents/_Work area/Sendaride-ios/SendASitter/Pods/CobrowseIO/CobrowseIO.framework/CobrowseIO' for architecture x86_64

**Comment by headlessme** [comment]
It looks like this issue was caused by Xcode updating. We've released Cobrowse SDK 1.9.2 which should fix builds with Xcode 10.2. Please re-open if this hasn't fixed the issue for you.
